export const getAllBranchFixedDepositQuery = (startDate: any, endDate: any) => {
    // tslint:disable-next-line: max-line-length
    return `select distinct gam.schm_code, gsp.schm_desc as ProductName, LTRIM(sol.sol_desc) BranchName,gam.sol_id BRANCHCODE, foracid ACCOUNTNO,gam.cif_id CustomerID,acct_name CustomerName, Acct_Opn_Date DateOpened,deposit_period_days TENOR, deposit_period_mths, ((deposit_period_mths*30)+ deposit_period_days) True_Tenor,maturity_date MATURITYDATE, acct_crncy_code,deposit_amount DEPOSITAMOUNT,system.int_rate_cr(foracid) INTERESTRATE, ((SELECT NRMl_BOOKED_AMOUNT_CR-NRML_INTEREST_AMOUNT_CR FROM TBAADM.EIT WHERE ENTITY_ID=gam.acid) + deposit_amount) clearedbalance, (SELECT NRMl_BOOKED_AMOUNT_CR-NRML_INTEREST_AMOUNT_CR FROM TBAADM.EIT WHERE ENTITY_ID=gam.acid) InterestPayable, Last_Tran_Date from tbaadm.tam,tbaadm.gam,tbaadm.itc, tbaadm.sol, tbaadm.gsp where tam.acid=gam.acid and itc.entity_id = gam.acid and gam.sol_id = sol.sol_id and Acct_Opn_Date between '${startDate}' and '${endDate}' and gam.schm_code = gsp.schm_code and GAM.DEL_FLG ='N' AND ACCT_CLS_FLG = 'N' AND GAM.schm_type in ('TUA','TDA') order by Branchname`;
};

export const getBranchFixedDepositQuery = (branchCode: any, startDate: any, endDate: any) => {
    // tslint:disable-next-line: max-line-length
    return `select distinct gam.schm_code, gsp.schm_desc as ProductName, LTRIM(sol.sol_desc) BranchName,gam.sol_id BRANCHCODE, foracid ACCOUNTNO,gam.cif_id CustomerID,acct_name CustomerName, Acct_Opn_Date DateOpened,deposit_period_days TENOR, deposit_period_mths, ((deposit_period_mths*30)+ deposit_period_days) True_Tenor,maturity_date MATURITYDATE, acct_crncy_code,deposit_amount DEPOSITAMOUNT,system.int_rate_cr(foracid) INTERESTRATE, ((SELECT NRMl_BOOKED_AMOUNT_CR-NRML_INTEREST_AMOUNT_CR FROM TBAADM.EIT WHERE ENTITY_ID=gam.acid) + deposit_amount) clearedbalance, (SELECT NRMl_BOOKED_AMOUNT_CR-NRML_INTEREST_AMOUNT_CR FROM TBAADM.EIT WHERE ENTITY_ID=gam.acid) InterestPayable, Last_Tran_Date from tbaadm.tam,tbaadm.gam,tbaadm.itc, tbaadm.sol, tbaadm.gsp where tam.acid=gam.acid and itc.entity_id = gam.acid and gam.sol_id = sol.sol_id and gam.sol_id = '${branchCode}' and Acct_Opn_Date between '${startDate}' and '${endDate}' and gam.schm_code = gsp.schm_code and GAM.DEL_FLG ='N' AND ACCT_CLS_FLG = 'N' AND GAM.schm_type in ('TUA','TDA') order by Branchname`;
};

